# CI/CD pipeline for RHKproperties
# Triggers on push to 'dev' branch

trigger:  
  branches:
    include:
    - deploy

variables:
- group: rhkproperties-site-dev  

pool:
  name: 'Self-Hosted-Runner-BOH-Dev'

steps:
- checkout: self

- script: |
    echo "Setting IMAGE_TAG to commit SHA: $(Build.SourceVersion)"
    echo "##vso[task.setvariable variable=IMAGE_TAG]$(Build.SourceVersion)"
  displayName: 'Set IMAGE_TAG dynamically to Commit SHA'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(IMAGE_TAG)

- script: |
    echo "Updating manifest: $(MANIFEST_PATH)"
    echo "New image: $(AZURE_CONTAINER_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)"
    sed -i "s|image: .*|image: $(AZURE_CONTAINER_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)|g" "$(MANIFEST_PATH)"
  displayName: 'Update Kubernetes manifest'

- task: Kubernetes@1
  displayName: 'Kube login (dev)'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure-AKS-BOH-dev'
    azureResourceGroup: '$(RESOURCE_GROUP)'
    kubernetesCluster: '$(CLUSTER_NAME)'
    namespace: '$(K8S_NAMESPACE)'
    command: 'login'

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure-AKS-BOH-dev'
    azureResourceGroup: '$(RESOURCE_GROUP)'
    kubernetesCluster: '$(CLUSTER_NAME)'
    namespace: '$(K8S_NAMESPACE)'
    command: 'apply'
    useConfigurationFile: true
    configuration: '$(MANIFEST_PATH)'